### ISSUE TITLE
[UWP] IRandomAccessStream does not support CloneStream - Zoomable Image

### ISSUE THREAD

**Issue by dansiegel** [TheEightBot/Aurora-Support#2]
**Describe the bug**

When running a UWP app with ZoomableImage it results in a System.NotSupportedException

**To Reproduce**

- Use ZoomableImage
- Run the UWP app

**Expected behavior**

I have a Zoomable Image

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Win 10 1809

**Smartphone (please complete the following information):**

**Additional context**

```
This IRandomAccessStream does not support the CloneStream method because it requires cloning and this stream does not support cloning.
   at System.IO.NetFxToWinRtStreamAdapter.ThrowCloningNotSupported(String methodName)
   at System.IO.NetFxToWinRtStreamAdapter.CloneStream()
--- End of stack trace from previous location where exception was thrown ---
   at Aurora.UWP.UWPIconCache.SKBitmapFromSource(ImageSource imageSource)
   at Aurora.Controls.ZoomableImage.<>c.<<-cctor>b__16_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__7_0(Object state)
   at System.Threading.WinRTSynchronizationContextBase.Invoker.InvokeCore()
```

**Comment by michaelstonis** [comment]
Can you provide which kind of image source you had provided when you encountered this crash?

**Comment by dansiegel** [comment]
technically it's binding to a string with a converter that returns an embedded resource like below

```cs
public object Convert(object value, Type targetType, object parameter, CultureInfo culture)
{
    if(parameter is string)
    {
        var resourceId = $"AwesomeApp.Images.{value}";
        return ImageSource.FromResource(question.ResourceId, GetType().Assembly);
    }

    return null;
}
```
